meta:
  environment: (( merge ))
  stemcell: (( merge ))

name: (( meta.environment ))

director_uuid: (( merge ))

releases: (( merge ))

networks: (( merge ))

jobs: (( merge ))

properties: (( merge ))

compilation:
  workers: 1
  network: (( properties.networks.apps ))
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000

resource_pools:
  - name: small_z1
    network: (( properties.networks.apps ))
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))
