meta:
  environment: (( merge ))
  dns_root: (( merge ))
  security_groups: (( merge ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

  networks:
    app: default

jobs:
  - name: zookeeper_z1
    instances: 3
    networks:
      - name: (( meta.networks.app ))
    persistent_disk: (( meta.persistent_disk ))
  - name: stardog_z1
    instances: 3
    networks:
      - name: (( meta.networks.app ))
    persistent_disk: (( meta.persistent_disk ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small
  - name: default
    network: (( meta.networks.app ))
    stemcell:
      name: bosh-aws-xen-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.small
      availability_zone: us-east-1a

properties:
  zookeeper:
    members: >
      <% 3.times do |i| %>
      <%= "- #{i}.zookeeper-z1.default.stardog-aws-ec2.microbosh\n" %>
      <% end %>
