networks: (( merge ))

meta:
  environment: ~
  networks:
    app: default

jobs:
  - name: zookeeper
    template: zookeeper
    instances: 0
    resource_pool: small_z1
    networks:
    - name: (( meta.networks.app ))
      static_ips: ~
  - name: stardog
    template:
    - stardog
    - proxy
    instances: 0
    resource_pool: small_z1
    networks:
    - name: (( meta.networks.app ))
      static_ips: ~
  

properties:
  networks:
    apps: (( meta.networks.app ))
  zookeeper:
    members: (( merge ))
