networks: (( merge ))

meta:
  environment: ~
  networks:
    app: default

jobs:
  - name: zookeeper
    templates:
    - {name: zookeeper, release: stardog}
    instances: 0
    resource_pool: small
    persistent_disk_pool: (( merge ))
    networks:
    - name: (( meta.networks.app ))
      static_ips: ~
  - name: stardog
    templates:
    - {name: stardog, release: stardog}
    - {name: proxy, release: stardog}
    instances: 0
    resource_pool: large
    persistent_disk_pool: (( merge ))
    networks:
    - name: (( meta.networks.app ))
      static_ips: ~
  

properties:
  networks:
    apps: (( meta.networks.app ))
  zookeeper:
    members: (( merge ))
  stardog:
    java_args: (( merge || "~" ))
