compilation:
  cloud_properties:
    instance_type: m1.small
  network: default
  reuse_compilation_vms: true
  workers: 1
director_uuid: MYDIRECTORUUID
jobs:
- instances: 3
  name: zookeeper_z1
  networks:
  - name: default
    static_ips: null
  resource_pool: small_z1
  template: zookeeper
- instances: 3
  name: stardog_z1
  networks:
  - name: default
    static_ips: null
  resource_pool: small_z1
  template: stardog
meta:
  environment: stardog-aws-ec2
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
name: stardog-aws-ec2
networks:
- cloud_properties:
    subnet: MYSUBNET
  dns: [10.0.0.6]
  name: default
  type: dynamic
properties:
  networks:
    apps: default
  zookeeper:
    members:
    <% 3.times do |i| %>
    <%= "- #{i}.zookeeper-z1.default.stardog-aws-ec2.microbosh\n" %>
    <% end %>

releases:
- name: stardog
  version: latest
resource_pools:
- cloud_properties:
    instance_type: m1.small
  name: small_z1
  network: default
  size: 6
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 30000-60000
  max_in_flight: 1
  update_watch_time: 5000-60000

